#!/bin/bash
echo "- restarting nginx..."
docker restart ${PWD##*/}_web_1 > /dev/null 2>&1
echo "nginx restarted"
echo "- restarting php..."
docker restart ${PWD##*/}_php_1 > /dev/null 2>&1
echo "php restarted"
echo "restart complete"